#!/usr/bin/env bash

step=0.01

# Get volume and status and send to mako
volume=$(wpctl get-volume @DEFAULT_SINK@)
vol_value=$(echo "$volume" | awk '{print $2 * 100}')
vol_status=$(echo "$volume" | cut -d" " -f3)

if [ "$vol_status" = "[MUTED]" ]; then
    notify-send -a "muted" -h int:value:"$vol_value" ""
    exit 0
fi

notify-send -a "volume" -h int:value:"$vol_value" ""
